name: benchmark
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Bazelisk
        run: |
         curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.18.0/bazelisk-linux-amd64"
         chmod +x bazelisk-linux-amd64
         sudo mv bazelisk-linux-amd64 /usr/local/bin/bazelisk
      - name: Checkout
        uses: actions/checkout@v6
      - name: Benchmark
        run: |
          cd adventofcode/2023/day/14
          bazelisk run -c opt parabolic_reflector_dish
